[package]
name = "std-util"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
heck = "0.4.1"
pluralizer = "0.4.0"
rand = "0.8.5"
