[package]
name = "toasty-postgres"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
toasty-core = { path = "../../core" }

anyhow = "1"
rusqlite = { version = "0.32", features = ["bundled"] }
sqlx = { version = "0.8" }

tokio = "1"
