[package]
name = "toasty-cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
toasty-codegen = { path = "../codegen" }
toasty-core = { path = "../core" }

anyhow = "1.0"
clap = { version = "3.1.12", features = ["derive"] }
