[package]
name = "toasty-dynamodb"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
toasty-core = { path = "../../core" }
anyhow = "1"
aws-sdk-dynamodb = { version = "1.3.0", features = ["test-util"] }
aws-config = "1"
serde = { version = "1.0.196", features = ["derive"] }
serde_json = "1.0.113"
