[package]
name = "example-user-has-one-profile"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
toasty = { path = "../../src/toasty" }
toasty-dynamodb = { path = "../../src/db/ddb" }

tokio = { version = "1.18", features = ["full"] }
